### ISSUE TITLE
Point lands before invisible section instead of next visible one

### ISSUE THREAD

**Issue by uu1101** [magit/magit#1771]
When `line-move-visual` is `nil`, issuing `next-line` on the `magit-status` buffer does not move point to the next visible header, it moves it just before the following invisible header.  This causes the cursor to look positioned at the next visible heading, when actually`(point)` is just before the next hidden header. [*] 

The following function can help in reproducing the issue:
~~~{.elisp}
(defun next-line-non-visual (&optional arg)
  (interactive)
  (or arg (setq arg 1))
  (let ((line-move-visual nil))
    (next-line arg)))
(global-set-key (kbd "C-S-n") #'next-line-non-visual)
~~~

The change below fixes the issue /on my machine/, but I admit that I do not understand what's going on on 9d55bcaf53627a06e4c149d6b42272509ad51f66:

~~~{.patch}
diff --git i/magit-mode.el w/magit-mode.el
index a7f16e7..d3b5254 100644
--- i/magit-mode.el
+++ w/magit-mode.el
@@ -264,9 +264,7 @@ Magit is documented in info node `(magit)'."
 
 (defun magit-post-command-adjust-point ()
   (when (and (get-text-property (point) 'invisible)
-             (not (if (fboundp 'get-pos-property) ; since 24.4, see #1671
-                      (get-pos-property (point) 'invisible)
-                    (get-text-property (1+ (point)) 'invisible))))
+             (get-text-property (1+ (point)) 'invisible))
     (goto-char (next-single-char-property-change (point) 'invisible))))
 
 (defvar-local magit-refresh-function nil)
~~~

This hapens to me as a user of the evil package: it is common to rebind `j` and `k` to `evil-{next,previous}-line`.  These let-bind `line-move-visual` to `nil` before invoking `{next,previous}-line`.

I know you are working hard on getting the release ready; rest  assured that this can wait for the next one.  As always, thank you very much for your effort.

Best regards,
uu1101.

Related to #1592.

[*]: This is quite difficult for me to explain, please ask for clarifications.

**Comment by tarsius** [comment]
I'll look into this later, but try to get it done before the release.

**Comment by tarsius** [comment]
The two debbugs are:

* http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19188
* http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19200

**Comment by tarsius** [comment]
I cannot reproduce this. Can anyone?

**Comment by uu1101** [comment]
I am sorry, failed to realize an important detail before: this issue happens on Emacs 24.3.1.  The issue does not seem to occur on Emacs 25.

Note that Emacs 24.3.1 is shipped with Ubuntu 14.04 LTS, and it seems there is no more up-to-date Emacs release packaged in any PPA.

**Comment by uu1101** [comment]
By the way, I'm using the following snippet to perform these tests in a clean way; it might be interesting providing this in the Makefile to make it easier for users to check bugs.

~~~{.patch}
diff --git i/Makefile w/Makefile
index 2d78dee..981e814 100644
--- i/Makefile
+++ w/Makefile
@@ -285,3 +285,6 @@ magit-$(VERSION).tar:
 genstats:
        @printf "Generating stats\n"
        @gitstats -c style=/css/stats.css -c max_authors=200 . $(statsdir)
+
+try:
+       $(EMACSBIN) -Q $(LOAD_PATH) -eval "(require 'magit)"

~~~

**Comment by uu1101** [comment]
Hmm... it seems that something similar happens on Emacs 25, only that the effect occurs in the opposite direction, on `prev-line'.  Please, try the following recipe:

~~~{.elisp}
(defun previous-line-non-visual (&optional arg)
  (interactive)
  (or arg (setq arg 1))
  (let ((line-move-visual nil))
    (previous-line arg)))
(global-set-key (kbd "C-S-p") #'previous-line-non-visual)
~~~

Using `C-S-p` does not move `(point)` to the previous hunk/file.

**Comment by tarsius** [comment]
Now overlays are used to hide section bodies. That should fix the issue with all supported Emacs releases. Let me know if it doesn't.

**Comment by uu1101** [comment]
Hmm... it seems that the issue is still present, although the details have changed: on Emacs 25 the issue is now visible when moving to _next_ line with `line-move-visual` set to `nil`.

There is another detail that I failed to realize before.  Again, I apologize for that.  The detail is that the issue seems to appear only when the movement is from column 0.

A recipe for reproducing the issue:

 1. Use the following helper code (same as before but prints point before and after movement):
    ~~~{.elisp}
(defun next-line-non-visual (&optional arg)
  (interactive)
  (or arg (setq arg 1))
  (let ((line-move-visual nil))
    (let ((ppos (point)))
      (next-line arg)
      (message "%s -> %s (next-...)" ppos (point)))))

(defun previous-line-non-visual (&optional arg)
  (interactive)
  (or arg (setq arg 1))
  (let ((line-move-visual nil))
    (let ((ppos (point)))
      (previous-line arg)
      (message "%s -> %s (previous-...)" ppos (point)))))

(global-set-key (kbd "C-S-n") #'next-line-non-visual)
(global-set-key (kbd "C-S-p") #'previous-line-non-visual)
    ~~~
 2. Move point to column 0 in a section whose children are hidden.
 3. Use C-S-n to move to next line, then C-S-p to go back to previous position.
 4. Move point to column 1.
 5. Use C-S-n to move to next line, then C-S-p to go back to previous position.
 6. See the output in `*Messages*` buffer:

    ~~~
"on column 0:"
208 -> 228 (next-...)
444 -> 208 (previous-...)
"on column 1:"
209 -> 445 (next-...)
445 -> 209 (previous-...)
    ~~~

    Note how the first movement lands in position 228 (just after the header and its newline, in `@` in my case).  Note also how when we move back, the position has changed to the right one 444 (due to some hook?  A mystery.)

I appreciate the effort you are putting into this.

Best regards,
uu1101.

**Comment by tarsius** [comment]
Okay I have now reproduced this.

The information you provided helped a lot narrowing down the issue, thanks a lot. Maybe there even isn't a bug/misfeature in the functionality described at `(elisp)Adjusting Point`.

The code paths `{previous,next}-line` end up taking when `line-move-visual` is `nil` contains code that inspects the invisible property. I suspect there is a bug/misfeature in how that is taken into account. Or in other words `line-move-1` does something that we don't want and which `line-move-visual` doesn't do. If you really want to fix this, then figure out what is going on in these functions.

But as far as Magit is concerned I will fix this simply by setting `line-move-visual` to `t` - I think that for the most part the value of this variable should not make a difference in Magit buffers (except for avoiding this issue of course).

At least for the time being, that is. But if you do investigate this further, then please let me know about your findings.

**Comment by uu1101** [comment]
That fixes the issue for users setting `line-move-visual` to nil in their configuration, but not for evil users (where `evil-{next,previous}-line` resets it prior to invoking `{next,previous}-line`).  I'll try to have a look at the function.  Thank you for having a look.

**Comment by tarsius** [comment]
> but not for evil users

I knew there was something about vi - but searching this page for spacemacs didn't return anything, remembered that wrong and then thought I remembered it completely wrong.

**Comment by tarsius** [comment]
Evil also provides `evil-{previous,next}-visual-line`. How would one rebind the respective keys to these variants in evil - `define-key`? Also maybe you could investigate how to do that just in Magit buffers.

**Comment by tarsius** [comment]
Does

```
(define-key magit-mode-map [remap evil-previous-line] 'evil-previous-visual-line)
(define-key magit-mode-map [remap evil-next-line] 'evil-next-visual-line)
```

work?

**Comment by uu1101** [comment]
Yes, that works nicely!  Thank you!

**Comment by tarsius** [comment]
I've installed the workaround.

**Comment by npostavs** [comment]
> Or in other words line-move-1 does something that we don't want and which line-move-visual doesn't do. If you really want to fix this, then figure out what is going on in these functions.

The difference is `line-move-visual` that calls `vertical-motion` with a cons which then performs column movement with `move-to-column`, but `line-move-1` calls it with just an int so in this case `vertical-motion` doesn't do column movement.  `line-move-1` does call `line-move-to-column` from `line-move-finish`, but it calls `beginning-of-line` (instead of `move-to-column`) when passed 0.

Compare:

```elisp
;; bad: returns point inside invisible section
(progn (vertical-motion 1) (point))
(progn (vertical-motion 1) (line-move-to-column 0) (point))
;; good: returns point after the section
(progn (vertical-motion '(0 . 1)) (point))
(progn (vertical-motion 1) (move-to-column 0) (point))
```

```
vertical-motion is a built-in function in `indent.c'.

(vertical-motion LINES &optional WINDOW)
...
LINES can optionally take the form (COLS . LINES), in which case the
motion will not stop at the start of a screen line but COLS column
from the visual start of the line...
```

-------------------------------------------------------------------------------

From 83b59be780b5ad8e177b1efa510e28373764746c:

```
There is one difference; when hiding a section body, we do *not* hide
the newline at the end of the heading but *do* hide the newline at the
end of the body - `outline-flag-region' does the opposite. That means
that hiding the body does not remove the background color of parts of
the heading - and that we cannot display an ellipsis at the "end of the
heading" (that wouldn't be visible).
```

What was the reason for this? From a quick check it seems that `outline-flag-region`'s method doesn't suffer from this problem.

-------------------------------------------------------------------------------

> Note also how when we move back, the position has changed to the
> right one 444 (due to some hook? A mystery.)

Since the the point is somehow corrected when the following command is run anyway, I don't quite understand what the user visible bug is here??

**Comment by tarsius** [comment]
> What was the reason for this?

You just quoted it:

> That means that hiding the body does not remove the background color of parts of the heading 

The background color of the newline character is used as the background color for the rest of the visual line. If we hide the newline character it's background color loses that effect.

**Comment by uu1101** [comment]
> Since the the point is somehow corrected when the following command is run anyway, I don't quite understand what the user visible bug is here??

I am sorry, it is very difficult for me to communicate the behaviour.

The user visible bug is that after using the helpers above, then pressing <kbd>TAB</kbd>, does not show the hunks for the file the cursor is over, but opens some kind of _phantom_ hunk of other file.  Please, see the images below:

 1. We start normally with the cursor over a section:

    ![magit1](https://cloud.githubusercontent.com/assets/552356/8958307/5f0eb692-3604-11e5-844a-eebd03fcde1a.png)

 2. Then we press <kbd>C-S-n</kbd> (bound to the helper above); note how the cursor is over the `magit-diff.el` section, but it is not highlighted:

    ![magit2](https://cloud.githubusercontent.com/assets/552356/8958306/5f0df0a4-3604-11e5-8b42-5fd790a7b6c0.png)

 3. Lastly we press <kbd>TAB</kbd> to see the `magit-diff.el` hunks, but instead we get a headerless hunk from the file above it:

    ![magit3](https://cloud.githubusercontent.com/assets/552356/8958308/5f0eee1e-3604-11e5-8b31-5e5bb58a4b31.png)

Thank you very much for your analysis and your time.

Best regards,
uu1101.

**Comment by npostavs** [comment]
@tarsius wrote
> You just quoted it:

Oh right, the "and" connective made me think it was 2 disadvantages, which actually makes no sense.

---

@uu1101 wrote
> I am sorry, it is very difficult for me to communicate the behaviour.

The whole thing is rather confusing, but your last post explains it beautifully, thank you.
