### ISSUE TITLE
Magit does not deal well with merge conflicts due to removed files

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#1988]
When merging two branches in which a file was removed on one side and modified on the other magit just shows the conflict as 'unmerged FILEXYZ' but doesn't give you any information about the type of conflict. When pressing 'TAB' on the magit status line for these conflicting files no additional information is shown.

git status on the command line would show useful information like:

```
$ git status
# # On branch branch-d
# # You have unmerged paths.
# #   (fix conflicts and run "git commit")
# #
# # Unmerged paths:
# #   (use "git add/rm ..." as appropriate to mark resolution)
# #
# #   deleted by us:      README.md
# #
# no changes added to commit (use "git add" and/or "git commit -a")
```

It would be nice if magit would show the 'deleted by us' or 'deleted by them' somewhere in the status buffer for such unmerged paths, maybe after pressing TAB?

Also, when resolving such a conflict one typically uses 'git rm' or 'git add' to either discard the change to the removed file, or to readd the entire file back to the index. Sometimes, when renames are involved, more complicated steps are necessary of course. In magit I don't know how to do either of these, so I usually fall back to the command line.

Any ideas how to deal with this?

**Comment by tarsius** [comment]
> Also, when resolving such a conflict one typically uses 'git rm' or 'git add' to either discard the change to the removed file, or to readd the entire file back to the index. Sometimes, when renames are involved, more complicated steps are necessary of course. In magit I don't know how to do either of these, so I usually fall back to the command line.

Use <kbd>k</kbd>, it will offer to keep one side (and discard the other).

**Comment by tarsius** [comment]
> It would be nice if magit would show the 'deleted by us' or 'deleted by them' somewhere in the status buffer for such unmerged paths, 

I have implemented that now.

**Comment by bastianbeischer** [comment]
Thanks a lot @tarsius for the perfect fix for the status buffer.

One problem remains: Using <kbd>k</kbd> seems like the solution I was looking for, but it appears that, since magit-checkout-file runs 'git add' in the end the file is always added, no matter if I chose [o]urs or [t]heirs in the dialogue.

Example:

I have removed a file X in my local branch Y
I merge a branch Z which has changes in the with respect to the common ancestor in file X.

The magit-status buffer now correctly shows 'deleted by us' for the unmerged path.

After pressing <kbd>k</kbd> on the file, I chose '[o]urs' because I want to remove the file.

Since there is no :2:X in the index, the git checkout command does nothing, and the 'git add' adds it to the index, marking the conflict as resolved. I think that in this case one should run 'git rm' instead.

**Comment by bastianbeischer** [comment]
process buffer prints this:

```
  1 git … checkout --ours io/ReaderThread.hh
     error: path 'io/ReaderThread.hh' does not have our version

  0 git … add io/ReaderThread.hh
```

**Comment by tarsius** [comment]
Could you please create a script that produces all possible conflicts in a single merge.

https://github.com/git/git/blob/master/t/t7060-wtstatus.sh could serve as a starting point. Run it like `sh t7060-wtstatus.sh -v -d`.

**Comment by bastianbeischer** [comment]
I can do that, but since I'm busy at the moment it could take some time. I don't think it's necessary though.

Here's what I'm thinking:

Before invoking 'git checkout --ours FILE' or 'git checkout --theirs FILE' one should use 'git ls-files -u -- FILE' to check whether the index stage 2 (ours) or 3 (theirs) even exists.

If yes, then git checkout --ours/theirs FILE -> git add FILE is the right thing to do, as before.

If not, then it appears that the user wants to resolve the conflict by removing the file. I think in this case, one should ask for confirmation that FILE will be deleted and just run 'git rm FILE'.

What's your opinion?

**Comment by bastianbeischer** [comment]
I've tried to create a patch, but since I really don't know lisp I'm hesitant to open a PR...

```
diff --git a/lisp/magit.el b/lisp/magit.el
index b0fdd3c..3fd14be 100644
--- a/lisp/magit.el
+++ b/lisp/magit.el
@@ -1305,10 +1305,21 @@ inspect the merge and change the commit message.
                (insert it "\n"))
           (magit-run-git-with-input nil "checkout" arg file))
         (magit-refresh))
-    (magit-call-git "checkout" arg file)
-    (if (string= arg "--merge")
-        (magit-refresh)
-      (magit-run-git "add" file))))
+    (let ((stages (magit-git-lines "ls-files" "-s" file))
+          (found 'nil))
+      (dolist (stage stages)
+        (when (or (and (string= arg "--ours") (string-match " 2\t" stage))
+                  (and (string= arg "--theirs") (string-match " 3\t" stage)))
+          (setq found t)))
+      (if (and (or (string= arg "--ours")
+                   (string= arg "--theirs"))
+               (not found))
+          (when (y-or-n-p (format "Remove file %s? " file))
+            (magit-call-git "rm" file))
+        (magit-call-git "checkout" arg file)
+        (if (string= arg "--merge")
+            (magit-refresh)
+          (magit-run-git "add" file))))))
 
 (defun magit-merge-state ()
   (file-exists-p (magit-git-dir "MERGE_HEAD")))
```
