### ISSUE TITLE
Can't reclaim authorship if there's nothing staged

### ISSUE THREAD

**Issue by mgalgs** [magit/magit#2276]
When I accidentally commit something with the wrong authorship information the way I usually fix it is with `c -R e` (i.e. `pop-up commiting` => `Claim authorship and reset author date` => `Extend`), which is equivalent to:

    git commit --amend --no-edit --reset-author

However, this recently started error'ing out with:

    user-error: Nothing staged (or unstaged)

This check seems to have been introduced by 00aec0a082f8f55cd40ebfb4bc8cc7dd40596b93 so I'm not sure why I'm only noticing it now... Maybe I just haven't used this feature for a few months and suddenly I've needed to use it multiple times this week :)

---

    M-x magit-version
    Magit 20150916.450, Git 2.5.2, Emacs 25.0.50.1

**Comment by npostavs** [comment]
This reminds me that I was trying to fix this for `--author=` and I noticed this too.

https://github.com/magit/magit/compare/master...npostavs:np/extend-author

**Comment by tarsius** [comment]
You should use the "vanilla amend" using <kbd>c-Ra</kbd> and then <kbd>C-cC-c</kbd> without editing the message.

"Extend" is for adding more changes to HEAD and I don't think it would make sense for it to behave differently when these arguments are set.

While you can use the "reword" variant to do this you shouldn't because you would otherwise end up with a commit which was "committed before it was authored". The same would apply to the "extend" variant if we added a special case to allow such usage.

**Comment by npostavs** [comment]
> You should use the "vanilla amend" using <kbd>c-Ra</kbd> and then <kbd>C-cC-c</kbd> without editing the message.

I was under the impression that the whole point of "extend" is to skip "then <kbd>C-cC-c</kbd> without editing the message". The manual's describes it as

> - Key: c e, magit-commit-extend

>  Amend the last commit, without editing the message.

But now you seem to be saying that preserving the date is the more (or at least equally) important feature. It seems a bit obscure, how often does anyone compare the commiter and author dates anway?

**Comment by tarsius** [comment]
> Amend the last commit, without editing the message.

I think the name and date changing arguments weren't available from the popup when I wrote that, so what I meant was:

* extend: add more changes to HEAD without editing the message
* reword: change HEAD's message without adding more changes

Both are optimized for the "I just made a mistake very recently and don't think it has to be recorded in the history" use case by not changing the committer date which allows you to pretend that there was no typo in what was first committed. The options `magit-commit-{extend and reword}` can be used to change that.

These variants weren't flexible enough, so I later added the "vanilla amend" variant which behaves just like `git commit --amend`. It can be used to change the patch and/or the message. And it always changes the committer date and name, there's no option to change that. It can also be used to change other commit metadata using the arguments the two of you have mentioned. That comes at the price of having to needlessly look at the commit message and type <kbd>C-cC-c</kbd> when one doesn't actually want to change the message. But since that isn't all that cumbersome and also what you would have to do every time when invoking `git commit --amend` on the command line, I think that's okay. (Well there is `--no-edit`, but still.)

**Comment by mgalgs** [comment]
> While you can use the "reword" variant to do this, you shouldn't do so because you would end up with a commit which was "committed before it was authored". The same would apply to the "extend" variant if we added a special case to allow such usage.

Actually, if I run `commit --amend --no-edit --reset-author` from a `:` prompt it *does* reset the commit date (as well as the author date).  What am I missing?

**Comment by tarsius** [comment]
Ah yes. Extend and reword keep both dates the same by *setting* both of them, not by keeping both unchanged, as I claimed earlier. I have fixed that above.

**Comment by mgalgs** [comment]
Lots of words here but I still don't understand why you don't think `commit --amend --no-edit --reset-author` is a valid use-case...

**Comment by tarsius** [comment]
I am not saying that. I'm just saying that the "extend" action shouldn't do that (because its purpose is to add changes), which means that one of the variants that always have the user edit/review the message.

And I am implying that I do not want to add a "no edit" (`commit --amend --no-edit`) variant, because I expect that it wouldn't be used very often and mainly serve to confuse users. I am also not found of the idea of adding the `--no-edit` argument, again because that would be confusing (and apparently all of this already is confusing, so adding even potential for confusion is a big deal).

**Comment by mgalgs** [comment]
> I'm just saying that the "extend" action shouldn't do that (because its purpose is to add changes)

I can understand not wanting to add something else to the popup, but why restrict the `Extend` action?  People don't have to use it that way if they don't want to...

**Comment by mgalgs** [comment]
Side note, what am I doing wrong here:

```elisp
(defun m/magit-reset-author (args)
  "Resets the authorship information for the last commit"
  (interactive)
  (magit-run-git-async "commit" "--amend" "--no-edit" "--reset-author"))

(magit-define-popup-action 'magit-commit-popup
  "R" "Reset author" 'm/magit-reset-author)
```

When I popup the committing popup, I see my action in the list but when I press `R` it says "R isn't bound to any action".

**Comment by kyleam** [comment]
> When I popup the committing popup, I see my action in the list but
> when I press `R` it says "R isn't bound to any action".

I think the issue is that KEY should be a character.

**Comment by mgalgs** [comment]
Ah sorry, I needed `?R` instead of `"R"` and needed to fix the number of args:

```elisp
(defun m/magit-reset-author (&optional args)
  "Resets the authorship information for the last commit"
  (interactive)
  (magit-run-git-async "commit" "--amend" "--no-edit" "--reset-author"))

(magit-define-popup-action 'magit-commit-popup
  ?R "Reset author" 'm/magit-reset-author)
```

**Comment by mgalgs** [comment]
@kyleam yep, thanks!

**Comment by tarsius** [comment]
I'll leave this as is for now. Maybe this comes up again, and if it does then I'll take that as an additional data point and maybe reconsider. But for now I am assuming that most users would realize why "Extend" does not work when there are no changes that could be used to extend HEAD, and then just use the amend variant.
