### ISSUE TITLE
Push upstream is not reliable anymore

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2455]
There are problems with <kbd>P u</kbd> command. When I push something it sometimes just writes something like `running git …` in echo area and nothing happens no matter how long I wait. Sometimes it works. After the first incident I restarted (!) Emacs and then I was able to finally push my commits, for example.

I'm reporting this here without further investigation, because 1) I'm too tired to dig into this right now, 2) I hope you may have ideas why exactly this might happen, because I'm sure it's a recent regression, previously Magit worked without any problems.

**Comment by mrkkrp** [comment]
Now again. First time it worked, second time it prints:

```
run git … push -v --force-with-lease origin master:refs/heads/master
Pushing to https://github.com/something/something.git
```

and nothing happens.

**Comment by mrkkrp** [comment]
Now somehow I'm getting this:

```
unable to access 'https://github.com/something/something.git/': SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 ... [Hit $ to see buffer *magit-process: something for details]
```

I only hope it won't corrupt my data.

**Comment by mrkkrp** [comment]
Maybe it's problems with GitHub, but that is unlikely.

**Comment by tarsius** [comment]
Just to by sure, by

> it sometimes just writes something like `running git …` in echo area

you mean `running git … more words follow here` and not literally `running git …`, right?

**Comment by mrkkrp** [comment]
Yes, it prints `Running git ` and full command there, just as usual.

**Comment by tarsius** [comment]
I suspect this is an issue on the remote side. `git push` not finishing for a very long time or never at all,  has happened to me before, though usually not with Github. The SSL read error is probably just a symptom of that: the remote sends some partial data and then never follows up with the rest, resulting in an incomplete read.

**Comment by mrkkrp** [comment]
The SSL error happened because I pushed for the second time after waiting about 20 seconds. The second attemp succeeded and then the first attempt resulted in this after a while.

I'll continue to work tomorrow. If this proves to be something temporary, I'll close the issue. Thanks for response.

**Comment by mrkkrp** [comment]
The problem has seemingly disappeared. Closing.

**Comment by biancashouse** [comment]
Problem persists in 2022. Don't ya just love and respect Microsoft.
