### ISSUE TITLE
magit-list-repositories fails on deleted remote branch

### ISSUE THREAD

**Issue by nickmccurdy** [magit/magit#2904]
I am unable to use `M-x magit-list-repositories` because some of my repositories are checked into branches that have seen been deleted remotely. When I run `M-x magit-status` with one of these repositories, the local branch exists, but the remote branch is reported as gone (which is accurate). This causes an error with magit trying to get the default remote's matching branch.

## Expected
I intentionally leave some git repositories alone for a while because they're small and I don't want to delete them, so I would like this functionality to recover from missing remote branches.

## Actual
Error `(wrong-type-argument stringp nil)`.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("	" nil 0)
  split-string(nil "	")
  magit-rev-diff-count("HEAD" #("origin/use-https" 0 16 (face magit-branch-remote)))
  magit-repolist-column-unpulled-from-upstream("cbusjs.github.com")
  #[257 "\3018\300!\206	\302\207" ["cbusjs.github.com" 2 ""] 3 "\n\n(fn IT)"](("L<U" 3 magit-repolist-column-unpulled-from-upstream (:right-align t)))
  mapcar(#[257 "\3018\300!\206	\302\207" ["cbusjs.github.com" 2 ""] 3 "\n\n(fn IT)"] (("Name" 25 magit-repolist-column-ident nil) ("Version" 25 magit-repolist-column-version nil) ("L<U" 3 magit-repolist-column-unpulled-from-upstream (:right-align t)) ("L>U" 3 magit-repolist-column-unpushed-to-upstream (:right-align t)) ("Path" 99 magit-repolist-column-path)))
  #[257 "\211\211A\262\242\211\211\302\303\304\305\306\302\307	!\310\"\311\312%	\"!)D\207" [default-directory magit-repolist-columns vconcat mapcar make-byte-code 257 "\3018\300!\206	\302\207" vector [2 ""] 3 "\n\n(fn IT)"] 13 "\n\n(fn INPUT0)"](("cbusjs.github.com" . "/Users/nick/Repos/cbusjs.github.com"))
  mapcar(#[257 "\211\211A\262\242\211\211\302\303\304\305\306\302\307	!\310\"\311\312%	\"!)D\207" [default-directory magit-repolist-columns vconcat mapcar make-byte-code 257 "\3018\300!\206	\302\207" vector [2 ""] 3 "\n\n(fn IT)"] 13 "\n\n(fn INPUT0)"] (("5to6-codemod" . "/Users/nick/Repos/5to6-codemod") ("arduino-projects" . "/Users/nick/Repos/arduino-projects") ("async" . "/Users/nick/Repos/async") ("backend" . "/Users/nick/Repos/backend") ("BlokDust" . "/Users/nick/Repos/BlokDust") ("Bonfire" . "/Users/nick/Repos/Bonfire") ("bonfire-web" . "/Users/nick/Repos/bonfire-web") ("bootstrap-datepicker" . "/Users/nick/Repos/bootstrap-datepicker") ("bootstrap-datepicker-rails" . "/Users/nick/Repos/bootstrap-datepicker-rails") ("bootswatch" . "/Users/nick/Repos/bootswatch") ("brickhack2" . "/Users/nick/Repos/brickhack2") ("brosql" . "/Users/nick/Repos/brosql") ("bs3dp-test" . "/Users/nick/Repos/bs3dp-test") ("buzzword-generator" . "/Users/nick/Repos/buzzword-generator") ("cbusjs.github.com" . "/Users/nick/Repos/cbusjs.github.com") ("claudiamccurdy" . "/Users/nick/Repos/claudiamccurdy") ("coffee-code-book" . "/Users/nick/Repos/coffee-code-book") ("college-code-challenge" . "/Users/nick/Repos/college-code-challenge") ("commit-security-example" . "/Users/nick/Repos/commit-security-example") ("coolest_clock" . "/Users/nick/Repos/coolest_clock") ("copyboard" . "/Users/nick/Repos/copyboard") ("crazy-train" . "/Users/nick/Repos/crazy-train") ("csci-243" . "/Users/nick/Repos/csci-243") ("csci-261" . "/Users/nick/Repos/csci-261") ("Custom Flappy Bird" . "/Users/nick/Repos/Custom Flappy Bird") ("danamcc.github.io" . "/Users/nick/Repos/danamcc.github.io") ("developer-resources" . "/Users/nick/Repos/developer-resources") ("dotfiles" . "/Users/nick/Repos/dotfiles") ("electrogram" . "/Users/nick/Repos/electrogram") ("euphoria" . "/Users/nick/Repos/euphoria") ("filibuster" . "/Users/nick/Repos/filibuster") ("final" . "/Users/nick/Repos/final") ("FindTheAnagrams" . "/Users/nick/Repos/FindTheAnagrams") ("FixTheTreeTDD" . "/Users/nick/Repos/FixTheTreeTDD") ("FlyCast" . "/Users/nick/Repos/FlyCast") ("front_matter_ninja" . "/Users/nick/Repos/front_matter_ninja") ("game-off-2016" . "/Users/nick/Repos/game-off-2016") ("gamesonthetable" . "/Users/nick/Repos/gamesonthetable") ("garfield-manufacturing" . "/Users/nick/Repos/garfield-manufacturing") ("generator" . "/Users/nick/Repos/generator") ("ghlint" . "/Users/nick/Repos/ghlint") ("ghlint-web" . "/Users/nick/Repos/ghlint-web") ("gitthello" . "/Users/nick/Repos/gitthello") ("grid" . "/Users/nick/Repos/grid") ("guided-meditation-player" . "/Users/nick/Repos/guided-meditation-player") ("harimambura.github.io" . "/Users/nick/Repos/harimambura.github.io") ("helm" . "/Users/nick/Repos/helm") ("hollyhastings.github.io" . "/Users/nick/Repos/hollyhastings.github.io") ("homesick" . "/Users/nick/Repos/homesick") ("hubot-commute" . "/Users/nick/Repos/hubot-commute") ...))
  magit-list-repositories()
  funcall-interactively(magit-list-repositories)
  call-interactively(magit-list-repositories record nil)
  command-execute(magit-list-repositories record)
  execute-extended-command(nil "magit-list-repositories" "magit-list-repositories")
  funcall-interactively(execute-extended-command nil "magit-list-repositories" "magit-list-repositories")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

## Reproduction
`~/Repos` should be a directory of git repos, with at least one checked out onto a branch where `M-x magit-status` reports its remote branch as gone.

### Versions
> Magit 20161215.548, Git 2.11.0, Emacs 25.1.1, darwin

### Commands
- `M-: (customize-set-variable 'magit-repository-directories '(("~/Repos" 1)))`
- `M-x magit-list-repositories`

**Comment by tarsius** [comment]
Thanks for reporting. I have pushed a fix. Please verify that it works for you.

**Comment by nickmccurdy** [comment]
Thanks for the fast response! I'm not seeing updates on MELPA, should I install this through source?

**Comment by nickmccurdy** [comment]
I think I used the wrong format for the customize variable. It was `(("~/Repos" 1))`, now I set it to `(("~/Repos" . 1))` which is what the customize GUI generated. However, I still get an error.

## Actual
```
Debugger entered--Lisp error: (wrong-type-argument sequencep t)
  mapconcat(identity ("branch" t "remote") ".")
  magit-get-all("branch" t "remote")
  apply(magit-get-all ("branch" t "remote"))
  magit-get("branch" t "remote")
  magit-get-upstream-branch(t)
  magit-repolist-column-unpulled-from-upstream("5to6-codemod")
  #[257 "\3018\300!\206	\302\207" ["5to6-codemod" 2 ""] 3 "\n\n(fn IT)"](("L<U" 3 magit-repolist-column-unpulled-from-upstream (:right-align t)))
  mapcar(#[257 "\3018\300!\206	\302\207" ["5to6-codemod" 2 ""] 3 "\n\n(fn IT)"] (("Name" 25 magit-repolist-column-ident nil) ("Version" 25 magit-repolist-column-version nil) ("L<U" 3 magit-repolist-column-unpulled-from-upstream (:right-align t)) ("L>U" 3 magit-repolist-column-unpushed-to-upstream (:right-align t)) ("Path" 99 magit-repolist-column-path)))
  #[257 "\211\211A\262\242\211\211\302\303\304\305\306\302\307	!\310\"\311\312%	\"!)D\207" [default-directory magit-repolist-columns vconcat mapcar make-byte-code 257 "\3018\300!\206	\302\207" vector [2 ""] 3 "\n\n(fn IT)"] 13 "\n\n(fn INPUT0)"](("5to6-codemod" . "/Users/nick/Repos/5to6-codemod"))
  mapcar(#[257 "\211\211A\262\242\211\211\302\303\304\305\306\302\307	!\310\"\311\312%	\"!)D\207" [default-directory magit-repolist-columns vconcat mapcar make-byte-code 257 "\3018\300!\206	\302\207" vector [2 ""] 3 "\n\n(fn IT)"] 13 "\n\n(fn INPUT0)"] (("5to6-codemod" . "/Users/nick/Repos/5to6-codemod") ("arduino-projects" . "/Users/nick/Repos/arduino-projects") ("async" . "/Users/nick/Repos/async") ("backend" . "/Users/nick/Repos/backend") ("BlokDust" . "/Users/nick/Repos/BlokDust") ("Bonfire" . "/Users/nick/Repos/Bonfire") ("bonfire-web" . "/Users/nick/Repos/bonfire-web") ("bootstrap-datepicker" . "/Users/nick/Repos/bootstrap-datepicker") ("bootstrap-datepicker-rails" . "/Users/nick/Repos/bootstrap-datepicker-rails") ("bootswatch" . "/Users/nick/Repos/bootswatch") ("brickhack2" . "/Users/nick/Repos/brickhack2") ("brosql" . "/Users/nick/Repos/brosql") ("bs3dp-test" . "/Users/nick/Repos/bs3dp-test") ("buzzword-generator" . "/Users/nick/Repos/buzzword-generator") ("cbusjs.github.com" . "/Users/nick/Repos/cbusjs.github.com") ("claudiamccurdy" . "/Users/nick/Repos/claudiamccurdy") ("coffee-code-book" . "/Users/nick/Repos/coffee-code-book") ("college-code-challenge" . "/Users/nick/Repos/college-code-challenge") ("commit-security-example" . "/Users/nick/Repos/commit-security-example") ("coolest_clock" . "/Users/nick/Repos/coolest_clock") ("copyboard" . "/Users/nick/Repos/copyboard") ("crazy-train" . "/Users/nick/Repos/crazy-train") ("csci-243" . "/Users/nick/Repos/csci-243") ("csci-261" . "/Users/nick/Repos/csci-261") ("Custom Flappy Bird" . "/Users/nick/Repos/Custom Flappy Bird") ("danamcc.github.io" . "/Users/nick/Repos/danamcc.github.io") ("developer-resources" . "/Users/nick/Repos/developer-resources") ("dotfiles" . "/Users/nick/Repos/dotfiles") ("electrogram" . "/Users/nick/Repos/electrogram") ("euphoria" . "/Users/nick/Repos/euphoria") ("filibuster" . "/Users/nick/Repos/filibuster") ("final" . "/Users/nick/Repos/final") ("FindTheAnagrams" . "/Users/nick/Repos/FindTheAnagrams") ("FixTheTreeTDD" . "/Users/nick/Repos/FixTheTreeTDD") ("FlyCast" . "/Users/nick/Repos/FlyCast") ("front_matter_ninja" . "/Users/nick/Repos/front_matter_ninja") ("game-off-2016" . "/Users/nick/Repos/game-off-2016") ("gamesonthetable" . "/Users/nick/Repos/gamesonthetable") ("garfield-manufacturing" . "/Users/nick/Repos/garfield-manufacturing") ("generator" . "/Users/nick/Repos/generator") ("ghlint" . "/Users/nick/Repos/ghlint") ("ghlint-web" . "/Users/nick/Repos/ghlint-web") ("gitthello" . "/Users/nick/Repos/gitthello") ("grid" . "/Users/nick/Repos/grid") ("guided-meditation-player" . "/Users/nick/Repos/guided-meditation-player") ("harimambura.github.io" . "/Users/nick/Repos/harimambura.github.io") ("helm" . "/Users/nick/Repos/helm") ("hollyhastings.github.io" . "/Users/nick/Repos/hollyhastings.github.io") ("homesick" . "/Users/nick/Repos/homesick") ("hubot-commute" . "/Users/nick/Repos/hubot-commute") ...))
  magit-list-repositories()
  funcall-interactively(magit-list-repositories)
  call-interactively(magit-list-repositories record nil)
  command-execute(magit-list-repositories record)
  execute-extended-command(nil "magit-list-repositories" "magit-list-repo")
  funcall-interactively(execute-extended-command nil "magit-list-repositories" "magit-list-repo")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

## Versions
> Magit 20161219.633, Git 2.11.0, Emacs 25.1.1, darwin

**Comment by tarsius** [comment]
Sorry about that, there was a stupid mistake in my fix. So in another few hours...
