### ISSUE TITLE
"There is no thing at point that could be visited" on RET on submodule with diff.submodule=log

### ISSUE THREAD

**Issue by CyberShadow** [magit/magit#3618]
### Steps to reproduce

1. In a new directory, run this script:

   ```bash
   #!/bin/bash
   set -eu

   mkdir testdir
   cd testdir
   export HOME=$PWD
   git config --global diff.submodule log
   git config --global user.name 'Magit Testcase'
   git config --global user.email "$USER@$HOSTNAME"
   mkdir subrepo
   (
	   cd subrepo
	   git init .
	   git commit --allow-empty -m 'Initial commit'
   )
   git init .
   git add .
   git commit --allow-empty -m 'Initial commit'
   git -C subrepo commit --allow-empty -m 'Second commit'
   emacs -Q --eval "
   (progn
	 (require 'package)
	 (add-to-list 'package-archives
				  '(\"melpa\" . \"https://melpa.org/packages/\") t)
	 (package-initialize)
	 (package-refresh-contents)
	 (package-install 'magit)

	 (magit-status))"
   ```

2. In the `magit-status` window, place point on the `subrepo` line and press `RET`.

### Expected result

`magit` should open a `magit-status` buffer for the `subrepo` submodule, as in previous versions.

### Actual result

`magit` shows the message "There is no thing at point that could be visited".

### Versions

- Magit 20181010.2201, Git 2.19.0, Emacs 26.1, gnu/linux
- OS: Arch Linux x64

### Remarks

- For some inane reason I can't reproduce this with magit from git, only from MELPA. Thus, I've also been unable to bisect it.

- `diff.submodule=log` seems to be necessary to reproduce this issue.

**Comment by tarsius** [comment]
> For some inane reason I can't reproduce this with magit from git, only from MELPA. Thus, I've also been unable to bisect it. Maybe reinstall from Melpa?

I believe I fixed this with 59e3891fde37b2b0937b54ffdd685703614360ad.

**Comment by CyberShadow** [comment]
I did see that. The commit is from 21 days ago, but the problem can be reproduced now. The magit version above is one which is installed from MELPA, and in which the issue persists.
