### ISSUE TITLE
magit-patch-apply wrong-type-argument error

### ISSUE THREAD

**Issue by basil-conto** [magit/magit#3761]
1. `make emacs-Q`
2. <kbd>C-x</kbd><kbd>g</kbd>
3. <kbd>w</kbd><kbd>a</kbd>
   * Expected behaviour: read patch file name in minibuffer
   * Observed behaviour:

         Debugger entered--Lisp error: (wrong-type-argument symbolp (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)))
           transient-suffix-object()
           (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))
           call-interactively((lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)) nil nil)
           command-execute((lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)))

`magit-version`:

```
Magit v2.90.1-263-gd24296c2, Git 2.20.1, Emacs 27.0.50, gnu/linux
```

`emacs-version`:

```
In GNU Emacs 27.0.50 (build 7, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2019-02-25 built on thunk
Repository revision: 6a3b1aaa066dac28355ca5d09550947250108950
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description: Debian GNU/Linux buster/sid
```

**Comment by tarsius** [comment]
There was a bug in `magit-apply-patch`, but for me it didn't lead to the above error. I have pushed a fix--please try again.

**Comment by basil-conto** [comment]
Thanks @tarsius, but I'm still getting the same error even after commit c180c6e184d3eb6820ea7adbf7fb15cdbecfde39.

**Comment by basil-conto** [comment]
FWIW I deleted and reinstalled all my packages before reporting this, so I'm fairly confident it's not a matter of stale Elisp.

**Comment by basil-conto** [comment]
If I delete `~/.emacs.d/elpa/transient-20190224.1630/transient.elc` prior to `make emacs-Q`, I get the following backtrace instead:

```
Debugger entered--Lisp error: (wrong-type-argument symbolp (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)))
  get((lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)) transient--suffix)
  (and t (get (or command this-command) 'transient--suffix))
  (let* ((obj (and t (get (or command this-command) 'transient--suffix))) (obj (and obj (clone obj)))) (if obj (progn (transient-init-scope obj) (transient-init-value obj) obj) nil))
  (if transient--prefix (cl-find-if #'(lambda (obj) (eq (transient--suffix-command obj) (or command this-original-command))) transient--suffixes) (let* ((obj (and t (get (or command this-command) 'transient--suffix))) (obj (and obj (clone obj)))) (if obj (progn (transient-init-scope obj) (transient-init-value obj) obj) nil)))
  transient-suffix-object()
  (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))
  call-interactively((lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)) nil nil)
  command-execute((lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)))
```

**Comment by basil-conto** [comment]
I also get the following:

1. `make emacs-Q`
2. <kbd>C-x</kbd><kbd>g</kbd>
3. <kbd>w</kbd><kbd>?</kbd><kbd>a</kbd>

```
Debugger entered--Lisp error: (wrong-type-argument symbolp (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)))
  describe-function((lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)))
  transient--describe-function((lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show)))
  (if (eq this-original-command 'transient-help) (let* ((manpage (and t (eieio-oref transient--prefix 'man-page)))) (if manpage (transient--show-manpage manpage) (transient--describe-function (eieio-oref transient--prefix 'command)))) (transient--describe-function this-original-command))
  (progn (if (eq this-original-command 'transient-help) (let* ((manpage (and t (eieio-oref transient--prefix 'man-page)))) (if manpage (transient--show-manpage manpage) (transient--describe-function (eieio-oref transient--prefix 'command)))) (transient--describe-function this-original-command)))
  (closure (transient-resume-mode Man-notify-method t) (_) "Show the command doc-string." (progn (if (eq this-original-command 'transient-help) (let* ((manpage (and t ...))) (if manpage (transient--show-manpage manpage) (transient--describe-function (eieio-oref transient--prefix ...)))) (transient--describe-function this-original-command))))(#<transient-suffix transient-suffix-15755fabde04>)
  apply((closure (transient-resume-mode Man-notify-method t) (_) "Show the command doc-string." (progn (if (eq this-original-command 'transient-help) (let* ((manpage (and t ...))) (if manpage (transient--show-manpage manpage) (transient--describe-function (eieio-oref transient--prefix ...)))) (transient--describe-function this-original-command)))) #<transient-suffix transient-suffix-15755fabde04> nil)
  transient-show-help(#<transient-suffix transient-suffix-15755fabde04>)
  (let ((winconf (current-window-configuration))) (transient-show-help (if (eq this-original-command 'transient-help) transient--prefix (or (transient-suffix-object) this-original-command))) (setq transient--restore-winconf winconf))
  (progn (setq transient--helpp nil) (let ((winconf (current-window-configuration))) (transient-show-help (if (eq this-original-command 'transient-help) transient--prefix (or (transient-suffix-object) this-original-command))) (setq transient--restore-winconf winconf)) (fit-window-to-buffer nil (frame-height) (window-height)) (transient-resume-mode) (message "Type \"q\" to resume transient command.") t)
  (if (lookup-key transient--transient-map (this-single-command-raw-keys)) (progn (setq transient--helpp nil) (let ((winconf (current-window-configuration))) (transient-show-help (if (eq this-original-command 'transient-help) transient--prefix (or (transient-suffix-object) this-original-command))) (setq transient--restore-winconf winconf)) (fit-window-to-buffer nil (frame-height) (window-height)) (transient-resume-mode) (message "Type \"q\" to resume transient command.") t))
  (condition-case err (if (lookup-key transient--transient-map (this-single-command-raw-keys)) (progn (setq transient--helpp nil) (let ((winconf (current-window-configuration))) (transient-show-help (if (eq this-original-command 'transient-help) transient--prefix (or (transient-suffix-object) this-original-command))) (setq transient--restore-winconf winconf)) (fit-window-to-buffer nil (frame-height) (window-height)) (transient-resume-mode) (message "Type \"q\" to resume transient command.") t)) ((debug error) (message "transient-help: %S" err) nil))
  (if (called-interactively-p 'any) (setq transient--helpp t) (condition-case err (if (lookup-key transient--transient-map (this-single-command-raw-keys)) (progn (setq transient--helpp nil) (let ((winconf (current-window-configuration))) (transient-show-help (if (eq this-original-command ...) transient--prefix (or ... this-original-command))) (setq transient--restore-winconf winconf)) (fit-window-to-buffer nil (frame-height) (window-height)) (transient-resume-mode) (message "Type \"q\" to resume transient command.") t)) ((debug error) (message "transient-help: %S" err) nil)))
  transient-help()
  (cond ((transient-help) (transient--do-suspend) (setq this-command 'transient-suspend) (transient--pre-exit)) (t (setq this-command 'transient-undefined)))
  (cond ((memq this-command '(transient-update transient-quit-seq)) (transient--pop-keymap 'transient--redisplay-map)) ((and transient--helpp (not (memq this-command '(transient-quit-one transient-quit-all)))) (cond ((transient-help) (transient--do-suspend) (setq this-command 'transient-suspend) (transient--pre-exit)) (t (setq this-command 'transient-undefined)))) ((and transient--editp (not (memq this-command '(transient-quit-one transient-quit-all transient-help)))) (setq this-command 'transient-set-level)) (t (setq transient--exitp nil) (if (eq (let* ((fn (and t ...))) (if fn (let (...) (if ... ...) action) (progn (setq this-command ...) transient--stay))) transient--exit) (progn (transient--pre-exit)))))
  transient--pre-command()
```

**Comment by basil-conto** [comment]
How do you edebug `transient` when it takes over the entire keymap?

**Comment by tarsius** [comment]
> <kbd>a</kbd> Expected behaviour: read patch file name in minibuffer

It's actually more complicated than that.

`magit-patch-apply` may now act as either a prefix or suffix command.

If it is bound in a regular keymap or as the suffix of another prefix, then it acts as a prefix.  In that case it features some infix arguments and a single suffix command; itself.  When it is invoked as the suffix of itself, then it does not act as a prefix instead it calls `git apply` with the infix arguments and a file read in the minibuffer.

So to apply the patch at point you would have to type `w a a RET` or `W a a RET`.

Sometimes appears to go wrong when typing the first `a` in `w a` (try `W a` just in case).

----

The lambda from the backtrace is the lambda shared by all infix commands/arguments (they are all equal but not eq).  I don't know where that lambda is coming from in this case--`magit-patch-apply` is not an infix command.

Lets try some debug statements:

``` diff
diff --git a/lisp/transient.el b/lisp/transient.el
index c58349a..98d98f9 100644
--- a/lisp/transient.el
+++ b/lisp/transient.el
@@ -1173,6 +1173,7 @@ (defun transient--make-transient-map ()
           (oset obj key key))
         (let ((kbd (kbd key))
               (cmd (transient--suffix-command obj)))
+          (message "--- %S %S"  kbd cmd)
           (when-let ((conflict (and transient-detect-key-conflicts
                                     (transient--lookup-key map kbd))))
             (unless (eq cmd conflict)
```

Pressing `w a` should print:

```
--- "-3" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-p" magit-apply:-p
--- "-c" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-k" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-b" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-d" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-D" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-s" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "m" magit-am-apply-maildir
--- "w" magit-am-apply-patches
--- "a" magit-patch-apply
--- "s" transient-set
--- "" transient-save
--- [134217833] transient-history-prev
--- [134217835] transient-history-next
--- "" transient-quit-one
--- "" transient-quit-all
--- "" transient-suspend
--- "t" transient-toggle-common
--- "l" transient-set-level
--- "-i" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-c" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "-3" (lambda (obj value) (interactive (let ((obj (transient-suffix-object))) (list obj (transient-infix-read obj)))) (transient-infix-set obj value) (transient--show))
--- "a" magit-patch-apply
--- "s" transient-set
--- "" transient-save
--- [134217833] transient-history-prev
--- [134217835] transient-history-next
--- "" transient-quit-one
--- "" transient-quit-all
--- "" transient-suspend
--- "t" transient-toggle-common
--- "l" transient-set-level
```

**Comment by kyleam** [comment]
It looks like I can trigger the initial traceback (with c180c6e184d3eb682 checked out) if magit-patch.el isn't loaded and magit-autoloads.el doesn't exist.   Do we need this?

```diff
diff --git a/lisp/magit.el b/lisp/magit.el
index 1feb3b88..61d45159 100644
--- a/lisp/magit.el
+++ b/lisp/magit.el
@@ -572,6 +572,7 @@ (cl-eval-when (load eval)
   (require 'magit-obsolete)
   (require 'magit-submodule)
   (unless (load "magit-autoloads" t t)
+    (require 'magit-patch)
     (require 'magit-subtree)
     (require 'magit-ediff)
     (require 'magit-extras)
```

**Comment by tarsius** [comment]
> How do you edebug `transient` when it takes over the entire keymap?

There is code in place that is supposed to exit the transient state when an error occurs.  It is possible that there are places where an error can occur without without that kicking in.  Once I can reproduce the issue I might also be able to better deal with similar errors.

**Comment by tarsius** [comment]
Yes!

Thanks a lot @kyleam. And I also know now "where the lambda is coming from".

**Comment by basil-conto** [comment]
Thanks @kyleam and @tarsius, the transient works for me now.

>> How do you edebug `transient` when it takes over the entire keymap?

> There is code in place that is supposed to exit the transient state when an error occurs. It is possible that there are places where an error can occur without without that kicking in. Once I can reproduce the issue I might also be able to better deal with similar errors.

Okay, but edebugging is such a useful feature of Emacs that it'd be a shame to miss out on it (this is similar sentiment to that expressed in #3736).

**Comment by tarsius** [comment]
> Okay, but edebugging is such a useful feature of Emacs that it'd be a shame to miss out on it

Ah, for some reason I though you were talking about debug-on-error.

Supporting edebug might also be possible.  Please open a feature request in the `transient` issue tracker.

**Comment by basil-conto** [comment]
> Please open a feature request in the `transient` issue tracker.

Done, thanks!
