### ISSUE TITLE
Wrong indent in git log

### ISSUE THREAD

**Issue by svenssonaxel** [magit/magit#4123]
**VERSION:** `v2.90.1-979-gafe8bee5`

**EXPECTED:**

For lines with no commit, i.e. just graph organization, the indent should be n+1 spaces where n is the number of characters in the abbreviated commit hash, so in the example reproduced below 8+1=9 spaces like so:

```
86baef3d | *   origin/develop Merge pull...
         | |\  
         |/ /  
a001c165 | * Point the changelog...
```

**ACTUAL:**

In the example reproduced below, the number of spaces in the indent is 8, as if the number of characters in the abbreviated commit hash was 7 rather than 8 like so:

```
86baef3d | *   origin/develop Merge pull...
        | |\  
        |/ /  
a001c165 | * Point the changelog...
```

I suspect the conditions triggering this error might be:

* Sufficient number of commits to cause the abbreviated commit ID to become more than 7 characters.
* No references in .git/heads

**TO REPRODUCE:**

What follows is a real-world example. Run the following in a shell:

```
mkdir testrepo
cd testrepo
git init
git remote add "origin" https://github.com/WorldBrain/Memex.git
git fetch --all
```

* Start emacs using the command calculated by `magit-emacs-Q-command`.
* Find the directory of the repository created above and execute `M-x magit-status RET l a` to see the magit log.
* Notice that the abbreviated commit hashes are 8 characters long.

**Comment by kyleam** [comment]
Thanks for pointing to a public repo.  Here's what I see with Git 2.26.2 and `core.abbrev` set to `auto`:

```
86baef3d | * develop origin/develop Merge pull request #1035 from AriaMinaei/patch-1
         |/| 
a001c165 | * Point the changelog link to the correct URL
```

As discussed at gh-3034, `core.abbrev=auto` should make these visual glitches rare.  If it doesn't for a particular repo, you can set `core.abbrev` to a larger N than `auto` picks.

**Comment by svenssonaxel** [comment]
With Git 2.20.1 and core.abbrev set to auto, it gets even worse for me:

```
86baef3d | *   origin/develop Merge pull request #1035 from AriaMinaei/patch-1
 | |\  
 |/ /  
a001c165 | * Point the changelog link to the correct URL
```

This is the case even after creating a local branch.

Did I understand gh-3034 correctly, that this is more or less a no-fix? Git, as invoked by magit, always prints the graph to the left, so it would seem that it is magit that attempts to move the hashes to the left and creates the unalignment.

**Comment by kyleam** [comment]
> Did I understand [gh-3034](https://github.com/magit/magit/issues/3034) correctly, that this is more or less a no-fix?

With the commit that closed that issue, these mis-alignments should be very rare; it requires both HEAD~ and HEAD needing to be extended farther than `core.abbrev` in order to be unambiguous.

I apologize for not doing your steps exactly, though.  I cloned the repo.  I see you added it as a remote, but you're still on an unborn branch when calling `log --all`.  That makes a difference.  That means that `magit-abbrev-length` just defaults to 7 because HEAD and HEAD~ don't exist.  That explains the first misaligned example you showed (and I can trigger misalignment on my end).  Once HEAD is define (you create a commit or check out an existing one), that misalignment should go way (and it does on my end).

As for the latest example you show, I'm baffled at how a one space indent would be produced.  That should not happen.

**Comment by kyleam** [comment]
> As for the latest example you show, I'm baffled at how a one space indent would be produced

I've triggered it.  I'll work on the fix for that later tonight.

**Comment by kyleam** [comment]
> > As for the latest example you show, I'm baffled at how a one space indent would be produced
> 
> I've triggered it. I'll work on the fix for that later tonight.

That's fixed in master (82a4e36)

---

So the main issue here boils down to the fact that `magit-abbrev-length` falls back to 7 if `HEAD` or `HEAD~` isn't defined.  That typically happens in a fresh repo, in which case that answer is okay.  But the scenario you describe involves being on an unborn branch in a repo with enough history that Git's auto-scaled abbreviation would be greater than 7.

I've pushed to km/abbrev-length-rev-list what I think is a good way to handle this scenario.  I'll bring that into master in a day or two if no one raises objections.

**Comment by svenssonaxel** [comment]
Fix confirmed on my end. Thank you!

**Comment by irisjae** [comment]
This still happens for me. It seems all my hashes are 8 characters for this repository (other repositories are fine). `core.abbrev` is set to `auto` already. In fact, setting `core.abbrev` to any fixed value seems to fix this.

Anything else I should be checking?

```
829efa98 | | | | * commit 3
        | | | |/| 
        | | |/| | 
7af8e197 | | | | * commit 2
        | | | |/  
        | | |/|   
dcfcbaa5 | | * | origin/master commit 1
```
